34/erplace hardcoded copy with translations
specollective/insights-agent-web-app pull request #91
Opened 2022-12-16 17:56 UTC by dashcraft

Ticket Description
<-- Copy and paste or write the tickets description here-->

Description of Changes
<-- Brief description of the changes you made, files you touched, etc -->

Before and After for UI Updates
<-- You should have 2 images minimum, for desktop, 4 for mobile and desktop combined -->

Before:

After:

For PR Reviewer
 Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
 If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
 Does this file match the related tickets linked figma file, or does it pass the visual smell test?
 If this file contains javascript, does the javascript pass the smell test?
 If you don't feel super confident in your review, did you assign someone more senior to double check?

2022-12-16 18:01 UTC, YolineB requested changes

2022-12-16 18:01 UTC, YolineB commented on public/locales/en/translation.json
> +  "ConfirmationNotReceivedThird": "If you have tried previous steps and are still not receiving a text message, please contact us at 800-555-1234.",
The phone number is now just the "tech4all@buildjustly.org" email. Other than that, it looks good to me!

2022-12-16 18:02 UTC, YolineB approved these changes

2022-12-20 18:07 UTC, mjtribble approved these changes

2022-12-20 18:11 UTC, merged