Issue #93 Hispanic Origin Question
specollective/insights-agent-web-app pull request #98
Opened 2022-12-29 22:14 UTC by crystallynnvoss

Ticket Description
Fixes issue #93 

Description of Changes
Update surveys.js and translation.json to include additional options for hispanic origin question 

Before and After for UI Updates
<-- You should have 2 images minimum, for desktop, 4 for mobile and desktop combined -->

Before:

After:

For PR Reviewer
 Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
 If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
 Does this file match the related tickets linked figma file, or does it pass the visual smell test?
 If this file contains javascript, does the javascript pass the smell test?
 If you don't feel super confident in your review, did you assign someone more senior to double check?

2023-01-02 19:14 UTC, YolineB requested changes
Just the uncommenting and then it is good!

2023-01-02 19:14 UTC, YolineB commented on src/components/pages/SurveyPage.jsx
> +  // const auth = useAuth();
This can be uncommented

2023-01-02 19:14 UTC, YolineB commented on src/components/pages/SurveyPage.jsx
> +  // if (!auth.user.isAuthenticated) return <div>Unauthenticated</div>
These can be uncommented too :)

2023-01-02 19:14 UTC, YolineB commented on src/App.js
> +                // </RequireAuth>
These can also be uncommented

2023-01-02 20:27 UTC, crystallynnvoss commented
@YolineB ok should be good to go

2023-01-03 18:08 UTC, YolineB approved these changes
LGTM!

2023-01-05 02:06 UTC, merged